// import accountsModel from '../models/accountsModel.js';
// import usersModel from '../models/usersModel.js';
// import {
//   findTransactionsWithCounterpartyName,
//   findTransactionsByUserId
// } from '../models/transactionsModel.js';

// /* ================================
//    Helpers
// ================================ */

// const toIso = (value) => {
//   if (!value) return null;
//   const date = new Date(value);
//   return Number.isNaN(date.getTime()) ? null : date.toISOString();
// };

// const startOfDay = (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate());
// const endOfDay = (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate(), 23, 59, 59, 999);

// const parseRelativeDateToken = (value, now) => {
//   const raw = String(value || '').trim().toLowerCase();
//   if (!raw) return null;

//   if (raw === 'now' || raw === 'today' || raw === 'היום') return now;
//   if (raw === 'yesterday' || raw === 'אתמול') {
//     return new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1);
//   }

//   if (
//     raw === 'this month' ||
//     raw === 'current month' ||
//     raw === 'החודש' ||
//     raw === 'בחודש הזה' ||
//     raw === 'בחודש הנוכחי' ||
//     raw === 'חודש נוכחי'
//   ) {
//     return new Date(now.getFullYear(), now.getMonth(), 1);
//   }

//   if (
//     raw === 'last month' ||
//     raw === 'בחודש האחרון' ||
//     raw === 'חודש אחרון'
//   ) {
//     return new Date(now.getFullYear(), now.getMonth() - 1, 1);
//   }

//   if (
//     raw === 'last 30 days' ||
//     raw === '30 days' ||
//     raw === '30d' ||
//     raw === '30 יום אחרונים'
//   ) {
//     return new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
//   }

//   const asDate = new Date(raw);
//   if (!Number.isNaN(asDate.getTime())) return asDate;
//   return null;
// };

// /*
//   תיקון חשוב:
//   - אם from/to ריקים או ""
//   - לא נפסול
//   - רק אם המשתמש שלח תאריך לא חוקי בפועל → נחזיר null
// */
// const toDateRange = (from, to) => {
//   const now = new Date();

//   const hasFrom = typeof from === 'string' && from.trim() !== '';
//   const hasTo = typeof to === 'string' && to.trim() !== '';

//   let start = hasFrom
//     ? parseRelativeDateToken(from, now)
//     : new Date(now.getFullYear(), now.getMonth(), 1);

//   let end = hasTo
//     ? parseRelativeDateToken(to, now)
//     : now;

//   if (!hasTo && hasFrom) {
//     const fromToken = String(from || '').trim().toLowerCase();
//     if (
//       fromToken === 'last month' ||
//       fromToken === 'בחודש האחרון' ||
//       fromToken === 'חודש אחרון'
//     ) {
//       end = new Date(now.getFullYear(), now.getMonth(), 0, 23, 59, 59, 999);
//     }
//   }

//   const invalidFrom = hasFrom && (!start || Number.isNaN(start.getTime()));
//   const invalidTo = hasTo && (!end || Number.isNaN(end.getTime()));

//   // Graceful fallback for loose natural-language tokens generated by the model.
//   // If only one bound is invalid, default to last 30 days instead of hard-failing.
//   if (invalidFrom || invalidTo) {
//     if (invalidFrom && invalidTo) return null;
//     start = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
//     end = now;
//   }

//   start = startOfDay(start);
//   end = endOfDay(end);

//   if (start > end) {
//     return null;
//   }

//   return { start, end };
// };

// /* ================================
//    Tool Definitions
// ================================ */

// export const bankTools = [
//   {
//     type: 'function',
//     function: {
//       name: 'get_user_identity',
//       description: 'Get authenticated user first name, last name and email',
//       parameters: { type: 'object', properties: {} }
//     }
//   },
//   {
//     type: 'function',
//     function: {
//       name: 'get_balance',
//       description: 'Get the authenticated user current account balance and status',
//       parameters: { type: 'object', properties: {} }
//     }
//   },
//   {
//     type: 'function',
//     function: {
//       name: 'get_last_transfer',
//       description: 'Get the most recent transfer (incoming or outgoing) for authenticated user',
//       parameters: { type: 'object', properties: {} }
//     }
//   },
//   {
//     type: 'function',
//     function: {
//       name: 'count_transfers',
//       description: 'Count user transfers in optional date range',
//       parameters: {
//         type: 'object',
//         properties: {
//           from: { type: 'string' },
//           to: { type: 'string' }
//         }
//       }
//     }
//   },
//   {
//     type: 'function',
//     function: {
//       name: 'get_last_sent_transfer_to_recipient',
//       description: 'Get recent transfers with a person by email local-part before @ (both outgoing and incoming)',
//       parameters: {
//         type: 'object',
//         properties: {
//           recipientName: { type: 'string' }
//         },
//         required: ['recipientName']
//       }
//     }
//   },
//   {
//     type: 'function',
//     function: {
//       name: 'get_recent_transfers',
//       description: 'Get recent transfers in optional date range for authenticated user',
//       parameters: {
//         type: 'object',
//         properties: {
//           limit: { type: 'number' },
//           from: { type: 'string' },
//           to: { type: 'string' }
//         }
//       }
//     }
//   }
// ];

// /* ================================
//    Tool Execution
// ================================ */

// export const executeBankTool = async ({ name, args = {}, userId }) => {

//   if (!userId) {
//     return { found: false, message: 'Unauthorized request' };
//   }

//   const safeArgs = args || {};

//   /* ---------- Identity ---------- */

//   if (name === 'get_user_identity') {

//     const user = await usersModel.findUserById(userId);

//     if (!user) {
//       return { found: false, message: 'User not found' };
//     }

//     return {
//       found: true,
//       firstName: user.firstName || '',
//       lastName: user.lastName || '',
//       email: user.email || ''
//     };
//   }

//   /* ---------- Balance ---------- */

//   if (name === 'get_balance') {

//     const account = await accountsModel.findAccountByUserId(userId);

//     if (!account) {
//       return { found: false, message: 'Account not found' };
//     }

//     return {
//       found: true,
//       balance: Number(account.balance) || 0,
//       status: account.status || 'UNKNOWN',
//       currency: 'ILS'
//     };
//   }

//   /* ---------- Last Transfer ---------- */

//   if (name === 'get_last_transfer') {

//     const transactions = await findTransactionsByUserId(userId);

//     if (!transactions?.length) {
//       return { found: false, message: 'No transactions found' };
//     }

//     const tx = transactions[0];

//     return {
//       found: true,
//       id: tx.id,
//       fromEmail: tx.fromEmail,
//       toEmail: tx.toEmail,
//       amount: Number(tx.amount) || 0,
//       status: tx.status,
//       description: tx.description || null,
//       createdAt: toIso(tx.createdAt)
//     };
//   }

//   /* ---------- Transfer Count ---------- */

//   if (name === 'count_transfers') {

//     const range = toDateRange(safeArgs.from, safeArgs.to);

//     if (!range) {
//       return { found: false, message: 'Invalid date range format' };
//     }

//     const transactions = await findTransactionsByUserId(userId);

//     if (!transactions?.length) {
//       return {
//         found: true,
//         count: 0,
//         from: range.start.toISOString(),
//         to: range.end.toISOString()
//       };
//     }

//     const count = transactions.filter((tx) => {
//       const createdAt = new Date(tx.createdAt);
//       return createdAt >= range.start && createdAt <= range.end;
//     }).length;

//     return {
//       found: true,
//       count,
//       from: range.start.toISOString(),
//       to: range.end.toISOString()
//     };
//   }

//   /* ---------- Transfers With Recipient (Bidirectional) ---------- */

//   if (name === 'get_last_sent_transfer_to_recipient') {

//     const recipientName = String(safeArgs.recipientName || '').trim();

//     if (!recipientName) {
//       return { found: false, message: 'recipientName is required' };
//     }

//     const transactions = await findTransactionsWithCounterpartyName(userId, recipientName);
//     const items = (transactions || []).slice(0, 10).map((tx) => ({
//       id: tx.id,
//       fromEmail: tx.fromEmail,
//       toEmail: tx.toEmail,
//       amount: Number(tx.amount) || 0,
//       status: tx.status,
//       description: tx.description || null,
//       createdAt: toIso(tx.createdAt)
//     }));

//     if (!items.length) {
//       return {
//         found: false,
//         message: `No transfers found with recipient ${recipientName}`
//       };
//     }

//     return {
//       found: true,
//       recipientName,
//       count: items.length,
//       items
//     };
//   }

//   /* ---------- Recent Transfers ---------- */

//   if (name === 'get_recent_transfers') {
//     const range = toDateRange(safeArgs.from, safeArgs.to);
//     if (!range) {
//       return { found: false, message: 'Invalid date range format' };
//     }

//     const requestedLimit = Number(safeArgs.limit);
//     const limit = Number.isFinite(requestedLimit)
//       ? Math.min(Math.max(Math.floor(requestedLimit), 1), 20)
//       : 3;

//     const transactions = await findTransactionsByUserId(userId);
//     const filtered = (transactions || []).filter((tx) => {
//       const createdAt = new Date(tx.createdAt);
//       return createdAt >= range.start && createdAt <= range.end;
//     });

//     const items = filtered.slice(0, limit).map((tx) => ({
//       id: tx.id,
//       fromEmail: tx.fromEmail,
//       toEmail: tx.toEmail,
//       amount: Number(tx.amount) || 0,
//       status: tx.status,
//       description: tx.description || null,
//       createdAt: toIso(tx.createdAt)
//     }));

//     return {
//       found: true,
//       count: items.length,
//       from: range.start.toISOString(),
//       to: range.end.toISOString(),
//       items
//     };
//   }

//   /* ---------- Fallback ---------- */

//   return {
//     found: false,
//     message: `Unsupported tool: ${name}`
//   };
// };

import accountsModel from '../models/accountsModel.js';
import usersModel from '../models/usersModel.js';
import {
  findTransactionsWithCounterpartyName,
  findTransactionsByUserId
} from '../models/transactionsModel.js';

/* ================================
   Date Helpers (unchanged but cleaner)
================================ */

const toIso = (value) => {
  if (!value) return null;
  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? null : d.toISOString();
};

const startOfDay = (d) =>
  new Date(d.getFullYear(), d.getMonth(), d.getDate());

const endOfDay = (d) =>
  new Date(d.getFullYear(), d.getMonth(), d.getDate(), 23, 59, 59, 999);

const parseRelativeDateToken = (value, now) => {
  const raw = String(value || '').toLowerCase().trim();
  if (!raw) return null;

  if (['now', 'today', 'היום'].includes(raw)) return now;

  if (['yesterday', 'אתמול'].includes(raw))
    return new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1);

  if (['this month', 'current month', 'החודש'].includes(raw))
    return new Date(now.getFullYear(), now.getMonth(), 1);

  if (['last month', 'חודש אחרון', 'בחודש האחרון'].includes(raw))
    return new Date(now.getFullYear(), now.getMonth() - 1, 1);

  if (['last 30 days', '30 days', '30 יום'].includes(raw))
    return new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

  const asDate = new Date(raw);
  return Number.isNaN(asDate.getTime()) ? null : asDate;
};

const toDateRange = (from, to) => {
  const now = new Date();

  let start = from
    ? parseRelativeDateToken(from, now)
    : new Date(now.getFullYear(), now.getMonth(), 1);

  let end = to ? parseRelativeDateToken(to, now) : now;

  if (!start || !end) return null;

  start = startOfDay(start);
  end = endOfDay(end);

  if (start > end) return null;

  return { start, end };
};

/* ================================
   TOOLS (clean + strict)
================================ */

export const bankTools = [
  { type: 'function', function: { name: 'get_user_identity', description: 'User identity', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'get_balance', description: 'Account balance', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'get_last_transfer', description: 'Last transfer', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'count_transfers', description: 'Count transfers', parameters: { type: 'object', properties: { from: { type: 'string' }, to: { type: 'string' } } } } },
  { type: 'function', function: { name: 'get_recent_transfers', description: 'Recent transfers', parameters: { type: 'object', properties: { limit: { type: 'number' }, from: { type: 'string' }, to: { type: 'string' } } } } },
  { type: 'function', function: { name: 'get_last_sent_transfer_to_recipient', description: 'Transfers with recipient', parameters: { type: 'object', properties: { recipientName: { type: 'string' } }, required: ['recipientName'] } } },

  /* UI ACTIONS */
  { type: 'function', function: { name: 'open_money_transfer', description: 'Open transfer UI', parameters: { type: 'object', properties: {} } } },
  { type: 'function', function: { name: 'open_video_call', description: 'Open video call UI', parameters: { type: 'object', properties: {} } } }
];

/* ================================
   EXECUTION
================================ */

export const executeBankTool = async ({ name, args = {}, userId }) => {
  if (!userId) return { found: false };

  if (name === 'open_money_transfer') return { found: true, action: 'open_money_transfer' };
  if (name === 'open_video_call') return { found: true, action: 'open_video_call' };

  if (name === 'get_user_identity') {
    const u = await usersModel.findUserById(userId);
    if (!u) return { found: false };
    return { found: true, firstName: u.firstName, lastName: u.lastName };
  }

  if (name === 'get_balance') {
    const a = await accountsModel.findAccountByUserId(userId);
    if (!a) return { found: false };
    return { found: true, balance: a.balance, status: a.status, currency: 'ILS' };
  }

  if (name === 'get_last_transfer') {
    const tx = (await findTransactionsByUserId(userId))?.[0];
    if (!tx) return { found: false };

    return {
      found: true,
      amount: tx.amount,
      fromEmail: tx.fromEmail,
      toEmail: tx.toEmail,
      createdAt: toIso(tx.createdAt)
    };
  }

  if (name === 'get_recent_transfers') {
    const range = toDateRange(args.from, args.to);
    if (!range) return { found: false };

    const txs = await findTransactionsByUserId(userId);

    const items = (txs || [])
      .filter((t) => {
        const d = new Date(t.createdAt);
        return d >= range.start && d <= range.end;
      })
      .slice(0, args.limit || 3)
      .map((t) => ({
        amount: t.amount,
        fromEmail: t.fromEmail,
        toEmail: t.toEmail
      }));

    return { found: true, items };
  }

  return { found: false };
};